### ISSUE TITLE
Addition of new fields under the Alumni Engagement module. 

### ISSUE THREAD

**Issue by Kirtigour** [gitmedha/sis-frontend#546]
In the student page, we have alumni engagement section. The below-mentioned fields are to be added under Alumni Engagement form. 

1. These fields should be accessible in the ADD alumni service form
2. These fields should be accessible in the EDIT alumni service form with saved values pre-selected
3. These fields should be visible in the Alumni Service Details popup (where we have edit & delete option)

### New Fields

**Program Mode**
- Type: Dropdown 
- Options: Offline/Online

**Category**: 
- Type: Dropdown 
- Options: Youth Leadership/Peer-Learning/Ideation Club/Giveback

#### Sub-Category Fields

**Youth Leadership**:
- Type: Dropdown
- Options: Young Leaders Journey/ Medhavi Voter
- Visible if the selected category is "Youth Leadership"

**Peer Learning**:
- Type: Dropdown
- Options: Rubaru/Career Chaupal/Atrangi/Workshop/Simmer/Day Out/HangOut/Alumni Meet/Alumni Parichay/Community project/Tik-Tok Challenge/Insta Video Diary
- Visible if the selected category is "Peer Learning"

**Ideation Club**:
- Type: Dropdown
- Options: Weekends With Walter (only 1 option)
- Visible if the selected category is "Ideation Club"

**Give Back**:
- Type: Dropdown
- Options: BEAM (only 1 option)
- Visible if the selected category is "Give Back"

**Comment by rathorevaibhav** [comment]
@Mariamraza15 @Kirtigour this is ready to test

**Comment by Kirtigour** [comment]
@rathorevaibhav, we need to remove the type field since we now have the sub-category field to avoid the data overlapping. 

And further, the Program Mode field can come under the Student. 

<img width="775" alt="image" src="https://github.com/gitmedha/sis-frontend/assets/106536464/d865f910-e9f2-4c75-a00b-050c13539d33">

**Comment by rathorevaibhav** [comment]
@Kirtigour @Mariamraza15 this is ready to test on staging site

**Comment by Kirtigour** [comment]
@rathorevaibhav, this looks good. Can be moved to production.

**Comment by Kirtigour** [comment]
@rathorevaibhav, I can not see any options in the dropdown under the category and in the program mode. 
<img width="643" alt="image" src="https://github.com/gitmedha/sis-frontend/assets/106536464/76ec6c83-a31f-442e-959f-8ef20d54b578">

**Comment by rathorevaibhav** [comment]
@Kirtigour it's fixed now. Can you please check?

**Comment by Kirtigour** [comment]
@rathorevaibhav, category I am able to see but I still can't see any dropdown in the Program Mode 
<img width="515" alt="image" src="https://github.com/gitmedha/sis-frontend/assets/106536464/80a4e252-0d64-4d56-87e7-229d1c5e3a27">

**Comment by rathorevaibhav** [comment]
@Kirtigour this is fixed also. Please check. There was a typo in the options list.
