### ISSUE TITLE
Paid field under the Opportunity module doesn't get ticked when selected Paid. 

### ISSUE THREAD

**Issue by Kirtigour** [gitmedha/sis-frontend#566]
While adding a new oppourtunity, when selected Paid, it does not reflect as selected when saved. Ideally, it should turn the colour green. 

Link of an oppourunity for your reference - https://sis-new.medha.org.in/opportunity/516

**Comment by deepaksharma9dev** [comment]
I have fixed and tested as well this issue in my local, I have requested Vaibhav to review and merge it into staging. then @Kirtigour @Mariamraza15  please test it and then we can move this to prod. Thanks

**Comment by Mariamraza15** [comment]
Not able to test this on staging because staging is not working.

**Comment by Mariamraza15** [comment]
@deepaksharma9dev The 'Paid' field is still grey (unticked) even when the value in the field is Yes. 
Link for your reference - https://sis-staging.medha.org.in/opportunity/2810

**Comment by deepaksharma9dev** [comment]
@Mariamraza15  I have fixed that and raised a pull request, once it gets merged you can review it, I have tested it locally it's working fine

**Comment by Kirtigour** [comment]
Hi @deepaksharma9dev, I tested it, and this is still not working on staging.  

Here is the link to the opportunity that I just created - https://sis-staging.medha.org.in/opportunity/5117

**Comment by Kirtigour** [comment]
@deepaksharma9dev, this is working fine on staging.

**Comment by Kirtigour** [comment]
This is working fine, @deepaksharma9dev.
